Repository LearnsMate/LearnsMateFrontend, pull requests merged in 2024-11, with the labels that each got.

#1 ✨ 기능 추가 : Learnsmate 프론트엔드 배포
  .github/workflows/deploy.yml
  Procfile
  package.json
  server.js
Labels: enhancement

#2 ✨ 기능 추가: 전체 페이지 SideMenu 추가
  src/App.vue
  src/components/AppHeader.vue
  src/components/sideMenu/LectureSideMenu.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/components/sideMenu/MemberSideMenu.vue
  src/components/sideMenu/VOCSideMenu.vue
  src/views/LectureView.vue
  src/views/MainView.vue
  src/views/MarketingView.vue
  src/views/MemberView.vue
  src/views/VocView.vue
Labels: enhancement

#4 ✨기능 추가 수정: MemberFilter 추가
  src/components/blacklist/BlacklistFilter.vue
  src/components/member/MemberFilter.vue
  src/views/MemberView.vue
Labels: frontend

#5 ✨ 기능 추가/수정: MemberView index 수정
  src/views/MemberView.vue
Labels: frontend

#7 ✨ 기능 추가: MarketingView 글목록 추가
  src/assets/css/style.css
  src/components/AppHeader.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/views/MarketingView.vue
Labels: enhancement

#10 ✨코드 추가 / 수정: MemberFilter 내용 및 위치 수정
  src/components/member/BlacklistFilter.vue
  src/components/member/MemberFilter.vue
Labels: frontend

#13 ✨기능 추가/수정: Member 전체 조회, 페이지네이션, 상세창 추가
  src/components/member/MemberFilter.vue
  src/components/sideMenu/MemberSideMenu.vue
  src/views/MemberView.vue
Labels: frontend

#15 ✨기능 추가: MarketingView 필터링 추가
  src/assets/icons/download.svg
  src/assets/icons/reset.svg
  src/assets/icons/search_white.svg
  src/components/member/CampaignFilter.vue
  src/views/MarketingView.vue
Labels: enhancement, frontend

#18 ✨기능 추가/수정: member filter 수정, blacklist view 추가
  src/components/AppHeader.vue
  src/components/member/MemberFilter.vue
  src/components/sideMenu/MemberSideMenu.vue
  src/router/member.js
  src/router/router.js
  src/views/member/BlacklistView.vue
  src/views/member/StudentBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorBlacklistView.vue
  src/views/member/TutorView.vue
Labels: bug, enhancement, ♻ refactor, frontend

#20 feat(#19): 쿠폰 전체 조회 화면
  src/router/router.js
  src/views/CouponView.vue
Labels: enhancement, frontend

#23 feat(#9): VOC 전체 조회 메인페이지 추가
  .github/workflows/deploy.yml
  Procfile
  src/assets/css/voc/VOCView.css
  src/components/voc/VOCFilter.vue
  src/views/VocView.vue
Labels: enhancement, frontend

#25 voc 관련 api 데이터 반환형 수정
  src/views/VocView.vue
Labels: ♻ refactor

#27 feat(#26): 전체 쿠폰 필터 적용 조회 화면 구현
  src/components/marketing/CouponFilter.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/router/marketing.js
  src/router/router.js
  src/views/CouponView.vue
Labels: enhancement, frontend

#24 TutorView, TutorBlacklist 기능 구현
  src/components/member/BlacklistFilter.vue
  src/components/member/MemberFilter.vue
  src/views/member/StudentBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorBlacklistView.vue
  src/views/member/TutorView.vue
Labels: bug, enhancement

#33 Feature/voc
  src/assets/css/voc/VOCView.css
  src/assets/icons/ai.svg
  src/assets/icons/voc_answer_register.svg
  src/components/voc/VOCFilter.vue
  src/router/router.js
  src/views/VocView.vue
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#34 ✨기능 추가/수정: Member, MemberBlacklist 애니메이션 삭제 및 css 수정
  src/views/member/StudentBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorBlacklistView.vue
  src/views/member/TutorView.vue
Labels: enhancement, frontend

#37 ✨기능 추가: Register-campaign 추가
  src/assets/icons/upload.svg
  src/components/AppHeader.vue
  src/components/marketing/CampaignFilter.vue
  src/components/marketing/TargetUserFilter.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/router/marketing.js
  src/views/marketing/CampaignRegisterPage.vue
  src/views/marketing/MarketingView.vue
Labels: enhancement, frontend

#40 ✨ 기능 추가: 로그인 오른쪽 공통 vuce 화면 기능 추가
  src/App.vue
  src/assets/icons/blue-greenlogo.svg
  src/assets/icons/footlogo.svg
  src/components/login/LoginLeft.vue
  src/components/login/LoginPwLeft.vue
  src/router/login.js
  src/router/router.js
  src/views/login/LoginView.vue
Labels: enhancement

#44 ✨ 기능 추가: 비활성화 모듈창 컴포넌트 구현
  src/components/modules/DeleteModule.vue
  src/components/modules/FalseModule.vue
  src/components/modules/RegisterModule.vue
Labels: enhancement

#65 ✨기능 추가: 학생 상세보기 추가/수정
  src/components/AppHeader.vue
  src/components/member/ReservedBlacklist.vue
  src/views/member/StudentBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorBlacklistView.vue
  src/views/member/TutorView.vue
Labels: enhancement, frontend

#69 feat(#32): 쿠폰 단 건 조회 화면 구현
  src/components/marketing/CouponDetail.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/router/marketing.js
  src/views/coupon/CouponView.vue
Labels: enhancement, frontend

#70 ✨ 기능 추가: 고객 - login Left .회원가입 2 컴포넌트 기능 추가
  src/App.vue
  src/assets/icons/Google.svg
  src/assets/icons/LearnsBuddy-login-logo.svg
  src/assets/icons/bluetechnologyback.svg
  src/assets/icons/kakao.svg
  src/components/client/login/ClientLoginLeft.vue
  src/components/client/login/ClientLoginSignupLeft.vue
  src/components/client/login/ClientLoginSignupLeft2.vue
  src/components/login/LoginLeft.vue
  src/components/login/LoginPwLeft.vue
  src/components/modules/RegisterModule.vue
  src/router/client.js
  src/router/login.js
  src/router/router.js
  src/views/client/login/ClientLoginView.vue
  src/views/login/LoginView.vue
Labels: bug, enhancement, frontend

#71 ♻️코드 변경: 쿠폰 조회 화면 수정
  src/components/marketing/CouponDetail.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/router/marketing.js
  src/views/coupon/CouponView.vue
Labels: ♻ refactor, frontend

#73 ✨기능 추가: 멤버 필터링 기능 추가 및 수정
  src/components/member/MemberFilter.vue
  src/router/marketing.js
  src/views/member/StudentView.vue
Labels: duplicate, enhancement, frontend

#74 voc 전체 조회 화면 구현
  src/assets/css/voc/VOCView.css
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#75 ✨기능 추가: TutorView 페이지네이션, 필터링 수정
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, backend, frontend

#76 VOC 메인 화면 DML 구문 이후 페이지네이션까지 구현 완료. api 테스트 완료
  src/assets/css/voc/VOCView.css
  src/components/voc/VOCFilter.vue
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#77 ✨ 기능 추가: 로그인 토큰 데이터 연결 기능 추가
  package-lock.json
  package.json
  src/components/login/LoginLeft.vue
  src/main.js
  src/stores/loginState.js
  src/views/MainView.vue
Labels: enhancement

#81 ✨기능 추가/수정: 멤버, 블랙리스트 조회 기능 수정
  package-lock.json
  package.json
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/components/member/ReservedBlacklist.vue
  src/components/sideMenu/MemberSideMenu.vue
  src/plugins/axios.js
  src/router/member.js
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorBlacklistView.vue
  src/views/member/TutorView.vue
Labels: bug, enhancement

#82 ✨ 기능 추가 : VOC 액셀 다운로드 기능 추가
  package-lock.json
  package.json
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#85 ♻️코드 수정: CampaignRegisterPage 수정
  package-lock.json
  package.json
  src/components/marketing/CampaignCouponSelectFilter.vue
  src/components/marketing/CampaignFilter.vue
  src/components/marketing/CampaignTemplateFilter.vue
  src/components/marketing/TargetUserFilter.vue
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/campaignTemplateRegisterModal.vue
  src/components/marketing/couponSelectModal.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
  src/views/marketing/campaignTemplate/CampaignTemplateGetPage.vue
Labels: enhancement

#86 VOC 액셀 다운로드 기능 추가 및 board-row 개수 증가 및 스크롤 추가
  src/assets/css/voc/VOCView.css
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#88 ✨ 기능 추가 : Lecture 전체 조회, 단 건 조회 구현
  src/assets/css/lecture/LectureView.css
  src/components/lecture/LectureFilter.vue
  src/router/router.js
  src/views/LectureView.vue
  src/views/lecture/LectureView.vue
Labels: frontend

#89 ✨ 기능 추가 : lecture 커서 페이지네이션 추가
  src/assets/css/lecture/LectureView.css
  src/views/lecture/LectureView.vue
Labels: enhancement, frontend

#91 ✨기능 추가: 고객, 블랙리스트 수정
  src/assets/css/member/BlacklistView.css
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: bug, enhancement, frontend

#95 lecture offset 페이지네이션으로 변경 및 필터링 기능 수정
  src/assets/css/lecture/LectureView.css
  src/components/lecture/LectureFilter.vue
  src/views/lecture/LectureView.vue
Labels: enhancement, ♻ refactor

#96 ✨기능 추가: 학생 상세조회 데이터 조회 추가
  src/assets/css/member/StudentView.css
  src/views/member/BlacklistView.vue
  src/views/member/StudentView.vue
Labels: bug, enhancement, backend, frontend

#97 formatDateFromArray 제거
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: frontend

#98 lecture 월별 데이터 그래프 추가 + 필터링 추가, 단 건 조회 시 클릭 -> 구매 전환율 그래프 추가 + 필터링 추가
  src/assets/css/lecture/LectureView.css
  src/components/lecture/MonthlyLectureModal.vue
  src/views/lecture/LectureView.vue
Labels: enhancement, frontend

#102 ♻️코드 수정: 뒤로가기 버튼 추가
  src/components/marketing/TargetUserSelectModal.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: frontend

#103 ✨기능 추가: 회원 엑셀 다운로드 기능 구현
  src/assets/css/member/StudentView.css
  src/plugins/axios.js
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: bug, enhancement, frontend

#104 ✨기능 추가: 블랙리스트 엑셀 다운로드, 회원 엑셀 업로드 추가
  src/views/member/BlacklistView.vue
  src/views/member/StudentView.vue
Labels: enhancement, frontend

#105 ✨기능 추가: 학생 카테고리 비율 chart 추가
  src/components/member/StudentCategoryRatioModal.vue
  src/views/member/StudentView.vue
Labels: enhancement, frontend

#108 ✨기능 추가: 엑셀 업로드 추가
  src/components/marketing/TargetUserSelectModal.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: enhancement

#109 feat(#30): 발급된 쿠폰 전체 조회 및 필터링 조회
  src/components/marketing/CouponDetail.vue
  src/components/marketing/CouponFilter.vue
  src/components/marketing/IssuedCouponDetail.vue
  src/components/marketing/IssuedCouponFilter.vue
  src/router/marketing.js
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
Labels: frontend

#111 ✨기능 추가: 캠페인 템플릿 전체 조회
  src/components/marketing/couponSelectModal.vue
  src/router/marketing.js
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement, frontend

#114 ✨기능 추가: 캠페인 템플릿 필터링 추가
  src/components/marketing/CampaignTemplateFilter.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement, frontend

#117 ✨기능 추가: 캠페인 단건 조회 추가
  src/components/marketing/CampaignCouponSelectFilter.vue
  src/components/marketing/CampaignTemplateGetModal.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement

#119 ✨기능 추가: 캠페인 템플릿 수정
  src/components/marketing/CampaignTemplateGetModal.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement, frontend

#123 ✨ 기능 추가: 직원 로그인시 토큰 쿠키에 담는 기능 추가
  src/components/login/LoginLeft.vue
  src/stores/loginState.js
  src/views/MainView.vue
Labels: enhancement, frontend

#124 ✨ 기능 추가: 직원 로그아웃 api 호출 기능 추가
  src/components/AppHeader.vue
  src/stores/loginState.js
Labels: enhancement, frontend

#128 ♻️코드 수정: 컴포넌트 위치 이동으로 인한 리팩토링
  src/composables/useActivityMonitor.js
  src/views/client/clientlecture/ClientCouponAddView.vue
  src/views/client/clientlecture/ClientLectureCart.vue
  src/views/client/clientlecture/ClientLectureDetail.vue
  src/views/client/clientlecture/ClientLectureView.vue
  src/views/client/clientlecture/ClientMyLectureView.vue
  src/views/client/clientmain/ClientMainView.vue
  src/views/client/clientvoc/ClientVOCMyView.vue
  src/views/client/clientvoc/ClientVOCView.vue
Labels: enhancement, ♻ refactor, frontend

#131 ✨ 기능 추가: 로그인 직원 관련 사번 및 부서 정보 기능 추가
  src/components/AppHeader.vue
  src/stores/loginState.js
Labels: enhancement

#132 VOC AI 모달 추가 및 Lecture 필터링 기능 수정 및 모달 디자인 수정 + 파일 위치 변경 및 텍스트 폰트 추가
  src/App.vue
  src/assets/css/style.css
  src/assets/css/voc/VOCView.css
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/fonts/font.css
  src/components/AppHeader.vue
  src/components/lecture/MonthlyLectureModal.vue
  src/components/sideMenu/LectureSideMenu.vue
  src/components/sideMenu/VOCSideMenu.vue
  src/components/voc/VOCEditModule.vue
  src/components/voc/VOCRegisterModule.vue
  src/components/voc/VocAiModal.vue
  src/views/lecture/LectureView.vue
  src/views/voc/VocView.vue
Labels: enhancement

#133 voc 답변 등록 시 새로 고침 안 되는 것 해결
  src/views/voc/VocView.vue
Labels: ♻ refactor

#134 ✨ 기능 추가: Main 페이지 뷰 기능 추가
  src/assets/css/voc/VOCView.css
  src/components/AppHeader.vue
  src/views/MainView.vue
Labels: enhancement, frontend

#136 ✨기능 추가: cookie 사용으로 인한 axios 수정, 강의 카테고리 한글화
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/components/member/BlackReason.vue
  src/components/member/ReservedBlacklist.vue
  src/components/member/StudentCategoryRatioModal.vue
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, frontend

#138 ✨기능 추가: 캠페인 템플릿 엑셀 파일 다운로드 추가
  src/components/sideMenu/MarketingSideMenu.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement

#140 ✨기능 추가: 필요컬럼 추가
  src/assets/css/member/StudentView.css
  src/views/member/StudentView.vue
Labels: frontend

#141 ♻️코드 수정: import 수정
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: ♻ refactor

#142 ✨기능 추가: StudentView memberDomrantFlat -> memberDormantStatus
  src/views/member/StudentView.vue
Labels: bug, frontend

#143 ✨기능 추가: 회원 view, css 변경
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, frontend

#144 ♻️코드 수정: 모달 오류 수정
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/campaignTemplateRegisterModal.vue
  src/components/marketing/couponSelectModal.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
Labels: frontend

#145 ♻️코드 변경: 쿠폰 등록 페이지 수정
  src/components/marketing/CouponDetail.vue
  src/components/marketing/CouponFilter.vue
  src/router/marketing.js
  src/views/coupon/CouponRegisterView.vue
  src/views/coupon/CouponView.vue
Labels: frontend

#148 ✨기능 추가: 컬럼 선택 기능 추가
  src/components/marketing/TargetUserSelectModal.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: enhancement, frontend

#149 ✨기능 추가 : 쿠폰 등록 완료 후 모달창 닫히도록 수정
  src/views/coupon/CouponRegisterView.vue
Labels: frontend

#150 💄 UI/스타일 파일 추가: 새 비밀번호 입력 창 생길 시, 비율 변경 스타일 추가
  src/components/login/LoginPwLeft.vue
Labels: enhancement, frontend

#154 ✨ 기능 수정: 직원 이메일 및 비밀번호 변수 기능 수정
  src/components/login/LoginPwLeft.vue
  src/stores/loginState.js
Labels: enhancement

#155 ✨ 기능 추가 : Payment 관련 페이지 추가
  src/assets/css/lecture/LectureView.css
  src/assets/css/payment/PaymentView.css
  src/assets/css/style.css
  src/assets/css/voc/VOCView.css
  src/components/lecture/MonthlyLectureModal.vue
  src/components/payment/PaymentFilter.vue
  src/components/payment/PaymentRevenueModal.vue
  src/components/sideMenu/MemberSideMenu.vue
  src/components/voc/VocAiModal.vue
  src/router/lecture.js
  src/router/router.js
  src/router/voc.js
  src/views/client/clientlecture/ClientCouponAddView.vue
  src/views/client/clientlecture/ClientLectureView.vue
  src/views/lecture/LectureView.vue
  src/views/payment/PaymentView.vue
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#158 feat(#151, #152, #153) 강의 조회 화면 수정
  src/components/marketing/CouponDetail.vue
  src/views/coupon/CouponRegisterView.vue
  src/views/coupon/CouponView.vue
Labels: bug, enhancement, frontend

#159 ✨기능 추가: exp(만료시간) 추가
  src/components/AppHeader.vue
  src/stores/loginState.js
Labels: enhancement, frontend

#160 ✨기능 추가: 쿠폰 화면 페이지네이션 적용
  src/views/coupon/CouponRegisterView.vue
  src/views/coupon/CouponView.vue
Labels: frontend
