Repository LearnsMate/LearnsMateFrontend, pull requests merged in 2024-12, with the labels that each got.

#163 ♻️코드 수정: 매개변수 오류 수정
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: frontend

#165 ✨기능 추가: 발송 수단 추가
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: enhancement, frontend

#167 💄코드 수정: css 수정
  src/components/marketing/CampaignFilter.vue
  src/components/marketing/CampaignTemplateFilter.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: frontend

#162 💄 UI/스타일 파일 추가 : svg 파일 경로 수정
  .github/workflows/deploy.yml
  src/assets/css/lecture/LectureView.css
  src/assets/css/payment/PaymentView.css
  src/assets/css/voc/VOCView.css
  src/components/client/clientlecture/ClientAddCouponModal.vue
  src/components/client/clientlogin/ClientLoginLeft.vue
  src/components/client/clientlogin/ClientLoginSignupLeft.vue
  src/components/client/clientlogin/ClientLoginSignupLeft2.vue
  src/components/login/LoginLeft.vue
  src/components/login/LoginPwLeft.vue
  src/components/marketing/CampaignTemplateGetModal.vue
  src/components/marketing/CouponDetail.vue
  src/components/marketing/TargetUserSelectModal.vue
  src/router/router.js
  src/views/client/clientlecture/ClientLectureView.vue
  src/views/client/clientvoc/ClientVOCMyView.vue
  src/views/client/clientvoc/ClientVOCView.vue
  src/views/coupon/CouponRegisterView.vue
  src/views/lecture/LectureView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
  src/views/member/BlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
  src/views/payment/PaymentView.vue
  src/views/voc/VocView.vue
Labels: ♻ refactor

#168 💄 UI/스타일 파일 추가: 토글 스타일 추가
  src/assets/css/lecture/LectureView.css
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/components/AppHeader.vue
  src/components/member/BlackReason.vue
  src/components/member/BlacklistFilter.vue
  src/components/member/MemberFilter.vue
  src/components/member/StudentCategoryRatioModal.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, frontend

#169 ✨기능 추가: 새로고침시 로그인 기능 유지되게 수정
  src/router/router.js
  src/views/member/StudentView.vue
Labels: enhancement, frontend

#171 ♻️코드 수정: 메인 페이지 수정
  src/views/MainView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: frontend

#172 ✨기능 추가/수정: admin 로그인 수정t
  src/components/AppHeader.vue
  src/components/client/clientvoc/ClientVOCModal.vue
  src/stores/loginState.js
Labels: enhancement

#180 ✨기능 추가: 학생이 수간중인 강의 개수 표시하는 로직 추가
  src/views/member/StudentView.vue
Labels: enhancement, frontend

#182 ✨기능 추가/수정: 쿠폰 등록 유형 필터 추가
  src/components/marketing/CouponFilter.vue
  src/views/coupon/CouponView.vue
Labels: frontend

#183 ♻️코드 수정: IssuedCoupon 수정
  src/components/marketing/IssuedCouponDetail.vue
  src/components/marketing/IssuedCouponFilter.vue
  src/views/coupon/IssuedCouponView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: frontend

#186 ✨기능 추가: IssueCouponView 컬럼 선택 추가
  src/views/coupon/IssuedCouponView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
Labels: enhancement

#189 ✨기능 추가: 강사 강의, 쿠폰 조회 및 쿠폰 등록
  src/components/client/clientlecture/ClientAddCouponModal.vue
  src/views/client/clientlecture/ClientCouponAddView.vue
  src/views/client/clientlecture/ClientLectureDetail.vue
Labels: enhancement, frontend

#191 ♻️코드 수정: IssueCouponView 엑셀 다운로드 수정
  src/views/coupon/IssuedCouponView.vue
Labels: frontend

#192 ✨ 기능 추가: 만료시간을 배열로 변환하는 함수 기능 축가
  src/components/AppHeader.vue
  src/stores/loginState.js
Labels: enhancement, frontend

#193 ♻️ 코드 수정 : 쿠폰 등록 시 강의 필터링 기능 추가
  src/views/coupon/CouponRegisterView.vue
Labels: enhancement

#194 ♻️코드 수정: 쿠폰 활성화 필터 적용 안되는 현상 수정
  src/components/marketing/CouponFilter.vue
Labels: enhancement

#195 ♻️코드 수정: MainView 수정
  src/views/MainView.vue
Labels: frontend

#196 💄 UI/스타일 파일 수정: 선택된 결제 행 컬러 수정
  src/assets/css/lecture/LectureView.css
  src/assets/css/payment/PaymentView.css
  src/components/AppHeader.vue
  src/components/lecture/MonthlyLectureModal.vue
  src/components/payment/PaymentRevenueModal.vue
  src/views/lecture/LectureView.vue
  src/views/payment/PaymentView.vue
Labels: enhancement, frontend

#197 ♻️코드 수정: CampaignCouponSelectFilter 수정
  src/components/marketing/CampaignCouponSelectFilter.vue
  src/components/marketing/IssuedCouponDetail.vue
  src/components/marketing/TargetUserFilter.vue
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/couponSelectModal.vue
  src/components/modules/DeleteModule.vue
  src/components/sideMenu/MarketingSideMenu.vue
  src/views/MainView.vue
  src/views/coupon/IssuedCouponView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
Labels: frontend

#198 ♻️코드 수정: 디자인 수정
  src/components/marketing/TargetUserFilter.vue
Labels: frontend

#200 ✨♻️기능 추가/수정: 블랙리스트, 예비블랙리스트, 학생, 강사 CSS 및 로직 수정
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/components/member/MemberFilter.vue
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, ♻ refactor, frontend

#201 ♻️코드 수정: MainView 마스킹 처리
  src/views/MainView.vue
Labels: frontend

#202 ♻️코드 수정: board-row padding 수정
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
Labels: frontend

#204 ♻️ 코드 수정: 화면 디자인 및 프론트 오류 수정
  src/assets/css/style.css
  src/components/marketing/CouponDetail.vue
  src/components/marketing/CouponFilter.vue
  src/views/coupon/CouponView.vue
  src/views/member/StudentView.vue
Labels: bug, frontend

#207 ✨♻️ 기능 추가/수정: student, blacklist, reservedBlacklist css 수정 및 student view 토글 추가
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: enhancement, ♻ refactor, frontend

#209 ✨기능 추가/수정: css 수정
  src/assets/css/member/BlacklistView.css
  src/components/marketing/CouponDetail.vue
  src/views/coupon/CouponView.vue
Labels: enhancement, frontend

#210 ✨♻️기능 추가/수정: 쿠폰 라우팅 수정 및 사이드메뉴 css 수정
  src/components/sideMenu/MarketingSideMenu.vue
  src/views/coupon/CouponRegisterView.vue
Labels: enhancement, frontend

#208 백엔드 배포 연동
  src/App.vue
  src/components/AppHeader.vue
  src/components/client/ClientHeader.vue
  src/components/client/clientlecture/ClientAddCouponModal.vue
  src/components/client/clientlogin/ClientLoginLeft.vue
  src/components/client/clientvoc/ClientVOCModal.vue
  src/components/lecture/MonthlyLectureModal.vue
  src/components/login/LoginLeft.vue
  src/components/login/LoginPwLeft.vue
  src/components/main/CategoryBarChart.vue
  src/components/main/RevenueComparisonChart.vue
  src/components/marketing/CampaignTemplateGetModal.vue
  src/components/marketing/CouponDetail.vue
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/campaignTemplateRegisterModal.vue
  src/components/marketing/couponSelectModal.vue
  src/components/member/StudentCategoryRatioModal.vue
  src/components/payment/PaymentRevenueModal.vue
  src/components/voc/VocAiModal.vue
  src/main.js
  src/plugins/axios.js
  src/router/client.js
  src/router/router.js
  src/stores/loginState.js
  src/utils/timer.js
  src/views/MainView.vue
  src/views/client/clientlecture/ClientCouponAddView.vue
  src/views/client/clientvoc/ClientVOCMyView.vue
  src/views/coupon/CouponRegisterView.vue
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
  src/views/lecture/LectureView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
  src/views/payment/PaymentView.vue
  src/views/voc/VocView.vue
  vite.config.js
Labels: enhancement

#215 ♻️ 코드 수정: loginState 예외인 url들 401 에러 예외를 위해 수정
  src/stores/loginState.js
Labels: ♻ refactor, frontend

#218 ♻️ 코드 수정: console.log 삭제
  src/views/coupon/CouponView.vue
Labels: ♻ refactor, frontend

#216 ✨기능 추가/수정: 마스킹처리, 생성일 수정일 등 통일, 학생, 강사, 블랙리스트 필터링 적용
  src/assets/css/lecture/LectureView.css
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/ReservedBlacklistView.css
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/couponSelectModal.vue
  src/views/lecture/LectureView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
  src/views/member/BlacklistView.vue
  src/views/member/ReservedBlacklistView.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
  src/views/payment/PaymentView.vue
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#219 ♻️ 코드 수정: 직원이 강사 쿠폰 수정, 삭제 시 에러 alert창 추가
  src/components/marketing/CouponDetail.vue
Labels: enhancement

#221 ✨기능 추가: voc, payment 컬럼 정렬 추가
  src/assets/css/lecture/LectureView.css
  src/assets/css/payment/PaymentView.css
  src/assets/css/voc/VOCView.css
  src/views/payment/PaymentView.vue
  src/views/voc/VocView.vue
Labels: enhancement, frontend

#223 ✨기능 추가/수정: 쿠폰, 발급 쿠폰 필터링 + 정렬 기능 추가
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
Labels: bug, enhancement, frontend

#226 ✨기능 추가: 캠페인 컬럼 정렬
  src/components/marketing/CampaignFilter.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
Labels: frontend

#227 ✨기능 추가: 쿠폰, 발급쿠폰 css 수정
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
Labels: enhancement, frontend

#229 ♻️코드 수정: StudentView 상세조회 css 수정
  src/assets/css/member/StudentView.css
  src/assets/css/member/TutorView.css
  src/components/client/clientlogin/ClientLoginLeft.vue
  src/components/marketing/CampaignFilter.vue
  src/components/member/StudentCategoryRatioModal.vue
  src/views/MainView.vue
  src/views/marketing/campaign/AllCampaignsGetPage.vue
  src/views/marketing/campaignTemplate/AllCampaignTemplatesGetPage.vue
  src/views/member/StudentView.vue
  src/views/member/TutorView.vue
Labels: frontend

#231 ♻️코드 수정: ReservedBlacklistView css 수정
  src/assets/css/member/ReservedBlacklistView.css
  src/components/AppHeader.vue
  src/components/marketing/TargetUserSelectModal.vue
  src/components/marketing/TimeSelect.vue
  src/views/marketing/campaign/CampaignGetPage.vue
  src/views/marketing/campaign/CampaignRegisterPage.vue
  src/views/member/ReservedBlacklistView.vue
Labels: frontend

#232 코드 수정: 쿠폰 단 건 조회 삭제처리 추가
  src/components/marketing/CouponDetail.vue
  src/views/coupon/CouponView.vue
Labels: ♻ refactor

#233 ✨기능 추가/수정: 메인뷰 전년도 대비 수익 그래프 수정
  src/views/MainView.vue
Labels: enhancement, frontend

#235 ♻️ 코드 수정: 쿠폰 단 건 조회 삭제 관련 css 수정
  src/components/marketing/CouponDetail.vue
Labels: ♻ refactor

#236 ✨기능 추가/수정: 학생 css 수정
  src/assets/css/member/StudentView.css
Labels: enhancement, frontend

#237 ♻️코드 수정: CampaignGetPage 수정
  src/components/voc/VOCCustomCalendar.vue
  src/components/voc/VocAiModal.vue
  src/views/marketing/campaign/CampaignGetPage.vue
Labels: frontend

#238 ♻️코드 수정: campaignGetPage 날짜 오류 수정
  src/views/marketing/campaign/CampaignGetPage.vue
Labels: frontend

#241 ♻️코드 수정: CampaignTemplateGetModal 수정
  src/components/marketing/CampaignCouponSelectFilter.vue
  src/components/marketing/CampaignTemplateGetModal.vue
Labels: frontend

#242 ✨기능 추가/수정: 쿠폰, 발급쿠폰 마스킹처리, 발급쿠폰, 쿠폰, 고객, 블랙리스트 css 수정
  src/assets/css/member/BlacklistView.css
  src/assets/css/member/StudentView.css
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
Labels: enhancement, frontend

#243 ♻️ 코드 수정: 블랙리스트 등록 계정 로그인 실패 alert 수정
  src/components/client/clientlogin/ClientLoginLeft.vue
Labels: ♻ refactor

#244 ♻️코드 수정: 캠페인 필터링 조회 오류 수정
  src/views/marketing/campaign/AllCampaignsGetPage.vue
Labels: frontend

#247 ✨기능 추가/수정: 쿠폰 등록시 전체 강의 선택시 선택 안되던 오류 수정
  src/views/coupon/CouponRegisterView.vue
Labels: enhancement, backend

#251 ♻️코드 수정: 쿠폰 필터링 기능 추가 후 마스킹 처리 추가
  src/views/coupon/CouponView.vue
  src/views/coupon/IssuedCouponView.vue
Labels: enhancement, frontend

#255 ♻코드 수정: voc ai 모듈 클릭시 처음 뜨는 날짜 데이터 한국 timezone에 맞게 수정
  src/components/voc/VocAiModal.vue
Labels: enhancement, frontend
